# Assignment 3 — Task 3
## Implementation of the Proposed NLP Architecture

**Students:** Raqib Hayat (NUM-BSCS-2022-40), Abu Bakar (NUM-BSCS-2022-41)

This notebook trains every model from `04_architecture_math.md` end-to-end
on the SentiUrdu-1M dataset and saves test-set predictions for
`03_evaluation.ipynb`.

For each of the two tasks we train seven models:

| Family | Models |
|---|---|
| Classical (TF-IDF) | Logistic Regression, Linear SVM |
| Deep Learning      | Multi-kernel CNN, BiLSTM + attention |
| Transformer        | mBERT, XLM-RoBERTa, Urdu-RoBERTa |

All models share:
- the same 8-step preprocessing pipeline (`preprocessing.py`),
- the same 70/15/15 stratified split (`seed=42`),
- inverse-frequency class weighting in the loss,
- identical metric computation in §10.

**Runtime knob.** Set `TRAIN_SUBSET` near the top of §1 to a smaller value
(e.g. 100_000) if you only have a few minutes; set it to `None` to use
the full corpus.

## 1 — Setup

In [1]:
# --- runtime / path setup -------------------------------------------------
import os, sys, warnings
warnings.filterwarnings("ignore")
os.environ.setdefault("PYTHONIOENCODING", "utf-8")
ROOT = os.path.dirname(os.path.abspath("__file__"))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import config
import preprocessing as pp
from config import (
    DATA_CSV, FIG_DIR, MODEL_DIR, RESULTS_DIR, CACHE_DIR, EMBED_DIR,
    SEED, set_seed,
    EMOTION_LABELS, SENTIMENT_LABELS,
    EMOTION_TO_SENTIMENT,
)
set_seed(SEED)
print(f"seed={SEED}   data csv: {DATA_CSV.exists()}")

seed=42   data csv: True

In [2]:
import json, time, gc
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

print("torch", torch.__version__, "cuda available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("device:", torch.cuda.get_device_name(0),
          f"({torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB)")

# ───── runtime knob ─────
TRAIN_SUBSET = None          # set e.g. 200_000 to debug end-to-end quickly
# Transformers can be very compute-heavy; if set, also caps the corpus seen
# by the transformer family only (classical + deep still use full data).
TRANSFORMER_TRAIN_SUBSET = None
# ────────────────────────

torch 2.12.0.dev20260222+cu128 cuda available: True
device: NVIDIA GeForce RTX 5070 Ti (17.1 GB)

## 2 — Load and label the dataset

In [3]:
%%time
raw = pd.read_csv(DATA_CSV, dtype=str, keep_default_na=False, na_values=[""])
raw["clean_text"] = pp.preprocess_series(raw["Text"])
raw["sentiment"]  = raw.apply(pp.build_sentiment_label, axis=1)
raw["emotion"]    = raw["Category"].map(pp.majority_emotion)

# Drop empty cleaned tweets (very few)
raw = raw[raw["clean_text"].str.len() > 0].reset_index(drop=True)
print(f"After dropping empty cleaned text: {len(raw):,} rows")

sentiment_df = raw.dropna(subset=["sentiment"]).reset_index(drop=True).copy()
emotion_df   = raw.dropna(subset=["emotion"]).reset_index(drop=True).copy()
print(f"Sentiment task: {len(sentiment_df):,} labelled rows")
print(f"Emotion task  : {len(emotion_df):,} labelled rows")

After dropping empty cleaned text: 1,046,828 rows
Sentiment task: 532,661 labelled rows
Emotion task  : 532,661 labelled rows
CPU times: total: 44.6 s
Wall time: 44.7 s

In [4]:
# Map text labels to integer ids
from config import SENT2ID, ID2SENT, EMOTION2ID, ID2EMOTION
sentiment_df["label"] = sentiment_df["sentiment"].map(SENT2ID)
emotion_df["label"]   = emotion_df["emotion"].map(EMOTION2ID)

print("Sentiment labels:", dict(sentiment_df["label"].value_counts().sort_index()))
print("Emotion labels  :", dict(emotion_df["label"].value_counts().sort_index()))

Sentiment labels: {0: np.int64(72081), 1: np.int64(1547), 2: np.int64(459033)}
Emotion labels  : {0: np.int64(459033), 1: np.int64(50375), 2: np.int64(2798), 3: np.int64(1837), 4: np.int64(17071), 5: np.int64(1547)}

## 3 — Stratified 70/15/15 split and persist

In [5]:
def stratified_split(df, label_col="label", seed=SEED):
    train, temp = train_test_split(df, test_size=0.30, stratify=df[label_col], random_state=seed)
    val, test  = train_test_split(temp, test_size=0.50, stratify=temp[label_col], random_state=seed)
    return train.reset_index(drop=True), val.reset_index(drop=True), test.reset_index(drop=True)

splits = {}
for task, df in [("sentiment", sentiment_df), ("emotion", emotion_df)]:
    tr, va, te = stratified_split(df)
    splits[task] = {"train": tr, "val": va, "test": te}
    for name, sub in splits[task].items():
        sub[["clean_text", "label"]].to_parquet(CACHE_DIR / f"{task}_{name}.parquet", index=False)
    print(f"{task}: train={len(tr):,}  val={len(va):,}  test={len(te):,}")

sentiment: train=372,862  val=79,899  test=79,900
emotion: train=372,862  val=79,899  test=79,900

In [6]:
if TRAIN_SUBSET:
    for task in splits:
        tr = splits[task]["train"]
        sub = tr.groupby("label", group_keys=False).apply(
            lambda g: g.sample(min(len(g), max(1, int(len(g) * TRAIN_SUBSET / len(tr)))),
                               random_state=SEED)
        )
        splits[task]["train"] = sub.reset_index(drop=True)
        print(f"  {task}: subsampled train -> {len(sub):,}")

## 4 — Classical: TF-IDF + Logistic Regression and Linear SVM

Section 4.1 / 4.2 of the math doc. We use the *same* TF-IDF vectoriser
for both classical models on each task; only the classifier head changes.

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
import joblib

def run_classical(task: str):
    tr, va, te = splits[task]["train"], splits[task]["val"], splits[task]["test"]
    labels = sorted(tr["label"].unique())
    print(f"\n=== {task.upper()} — TF-IDF + LR/SVM ===")

    vec_path = MODEL_DIR / f"tfidf_{task}.joblib"
    if vec_path.exists():
        vec = joblib.load(vec_path)
        Xtr = vec.transform(tr["clean_text"])
    else:
        vec = TfidfVectorizer(**config.TFIDF)
        Xtr = vec.fit_transform(tr["clean_text"])
        joblib.dump(vec, vec_path)
    Xva = vec.transform(va["clean_text"])
    Xte = vec.transform(te["clean_text"])
    ytr, yte = tr["label"].values, te["label"].values

    # ----- Logistic Regression -----
    lr = LogisticRegression(**config.LR)
    t0 = time.time(); lr.fit(Xtr, ytr); print(f"  LR fit: {time.time()-t0:.1f}s")
    pred_lr = lr.predict(Xte)
    joblib.dump(lr, MODEL_DIR / f"lr_{task}.joblib")
    pd.DataFrame({"y_true": yte, "y_pred": pred_lr}).to_csv(
        RESULTS_DIR / f"pred_{task}_lr.csv", index=False
    )

    # ----- Linear SVM -----
    svm_base = LinearSVC(**config.SVC_PARAMS)
    svm = CalibratedClassifierCV(svm_base, cv=3, method="sigmoid", n_jobs=-1)
    t0 = time.time(); svm.fit(Xtr, ytr); print(f"  SVM fit: {time.time()-t0:.1f}s")
    pred_svm = svm.predict(Xte)
    joblib.dump(svm, MODEL_DIR / f"svm_{task}.joblib")
    pd.DataFrame({"y_true": yte, "y_pred": pred_svm}).to_csv(
        RESULTS_DIR / f"pred_{task}_svm.csv", index=False
    )

    from sklearn.metrics import f1_score, accuracy_score
    for name, p in [("LR", pred_lr), ("SVM", pred_svm)]:
        print(f"  {name:>3}  acc={accuracy_score(yte, p):.4f}  "
              f"macro-F1={f1_score(yte, p, average='macro'):.4f}  "
              f"weighted-F1={f1_score(yte, p, average='weighted'):.4f}")

    return vec

In [8]:
vec_sent = run_classical("sentiment")
vec_emo  = run_classical("emotion")

=== SENTIMENT — TF-IDF + LR/SVM ===
  LR fit: 176.2s
  SVM fit: 14.7s
   LR  acc=0.6598  macro-F1=0.3852  weighted-F1=0.7107
  SVM  acc=0.8783  macro-F1=0.4004  weighted-F1=0.8409

=== EMOTION — TF-IDF + LR/SVM ===
  LR fit: 335.9s
  SVM fit: 33.8s
   LR  acc=0.3601  macro-F1=0.1632  weighted-F1=0.4959
  SVM  acc=0.8773  macro-F1=0.2087  weighted-F1=0.8347

## 5 — fastText Urdu embeddings download

The CNN and BiLSTM are initialised from the publicly released fastText
`cc.ur.300` vectors (Facebook AI). The file is ≈ 600 MB compressed; cached.

In [9]:
from urllib.request import urlretrieve
if not config.FASTTEXT_PATH.exists():
    print(f"Downloading fastText Urdu vectors to {config.FASTTEXT_PATH} ...")
    urlretrieve(config.FASTTEXT_URL, config.FASTTEXT_PATH)
    print("  done.")
else:
    print(f"Found fastText vectors at {config.FASTTEXT_PATH} "
          f"({config.FASTTEXT_PATH.stat().st_size/1e6:.1f} MB)")

Found fastText vectors at C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\embeddings\cc.ur.300.vec.gz (679.2 MB)

## 6 — Deep Learning: CNN + BiLSTM (PyTorch)

In [10]:
from torch.utils.data import DataLoader
import train_dl as tdl
from train_dl import Vocab, TweetDataset, make_collate, load_fasttext_vectors, compute_class_weights
from models_dl import TextCNN, BiLSTMAttn

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

def build_dataloaders(task: str, batch_size: int):
    tr, va, te = splits[task]["train"], splits[task]["val"], splits[task]["test"]
    vocab_path = CACHE_DIR / f"vocab_{task}.json"
    if vocab_path.exists():
        vocab = Vocab.from_json(vocab_path)
    else:
        vocab = Vocab.build(tr["clean_text"], max_size=config.VOCAB_SIZE, min_freq=2)
        vocab.to_json(vocab_path)
    print(f"  {task} vocab: {len(vocab):,} tokens (pad_id={vocab.pad_id}, unk_id={vocab.unk_id})")

    collate = make_collate(vocab.pad_id, config.MAX_LEN)
    def loader(df, shuffle):
        ds = TweetDataset(df["clean_text"].tolist(), df["label"].tolist(), vocab, config.MAX_LEN)
        return DataLoader(ds, batch_size=batch_size, shuffle=shuffle, num_workers=2,
                          pin_memory=True, collate_fn=collate)
    return vocab, loader(tr, True), loader(va, False), loader(te, False)

def fasttext_for(vocab: Vocab):
    emb_path = EMBED_DIR / f"ft_matrix_{len(vocab)}.pt"
    if emb_path.exists():
        return torch.load(emb_path)
    E = load_fasttext_vectors(config.FASTTEXT_PATH, vocab, dim=config.EMBED_DIM)
    torch.save(E, emb_path)
    return E

def run_dl(task: str, model_name: str):
    num_classes = 3 if task == "sentiment" else 6
    cfg = config.CNN if model_name == "cnn" else config.BILSTM
    print(f"\n=== {task.upper()} — {model_name.upper()} ===")

    vocab, tl, vl, tel = build_dataloaders(task, cfg["batch_size"])
    E = fasttext_for(vocab)
    if model_name == "cnn":
        model = TextCNN(
            vocab_size=len(vocab), num_classes=num_classes,
            embed_dim=config.EMBED_DIM,
            filter_sizes=cfg["filter_sizes"], num_filters=cfg["num_filters"],
            dropout=cfg["dropout"], padding_idx=vocab.pad_id,
            pretrained_embeddings=E,
        )
        needs_mask = False
    else:
        model = BiLSTMAttn(
            vocab_size=len(vocab), num_classes=num_classes,
            embed_dim=config.EMBED_DIM,
            hidden_size=cfg["hidden_size"], num_layers=cfg["num_layers"],
            dropout=cfg["dropout"], padding_idx=vocab.pad_id,
            pretrained_embeddings=E,
        )
        needs_mask = True
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"  trainable params: {n_params:,}")

    ytr_arr = np.asarray(splits[task]["train"]["label"].values, dtype=np.int64)
    cw = compute_class_weights(ytr_arr, num_classes)
    print(f"  class weights: {cw.tolist()}")

    out = tdl.train_model(
        model, tl, vl, class_weights=cw,
        lr=cfg["lr"], epochs=cfg["epochs"], patience=cfg["patience"],
        device=DEVICE, needs_mask=needs_mask,
    )

    y_true, y_pred = tdl.predict(model, tel, DEVICE, needs_mask)
    pd.DataFrame({"y_true": y_true, "y_pred": y_pred}).to_csv(
        RESULTS_DIR / f"pred_{task}_{model_name}.csv", index=False
    )
    torch.save(model.state_dict(), MODEL_DIR / f"{model_name}_{task}.pt")
    with open(MODEL_DIR / f"{model_name}_{task}.history.json", "w", encoding="utf-8") as f:
        json.dump({"history": out["history"], "best_val_acc": out["best_val_acc"]}, f)

    from sklearn.metrics import f1_score, accuracy_score
    print(f"  TEST  acc={accuracy_score(y_true, y_pred):.4f}  "
          f"macro-F1={f1_score(y_true, y_pred, average='macro'):.4f}  "
          f"weighted-F1={f1_score(y_true, y_pred, average='weighted'):.4f}")

    del model, tl, vl, tel
    torch.cuda.empty_cache(); gc.collect()

In [11]:
run_dl("sentiment", "cnn")
run_dl("sentiment", "bilstm")

=== SENTIMENT — CNN ===
  sentiment vocab: 58,851 tokens (pad_id=0, unk_id=1)
  trainable params: 18,117,639
  class weights: [2.4632327556610107, 114.76207733154297, 0.38679996132850647]
  epoch  1  step   100  loss 1.0700
  epoch  1  step   200  loss 1.0455
  epoch  1  step   300  loss 1.0289
  epoch  1  step   400  loss 1.0174
  epoch  1  step   500  loss 1.0132
  epoch  1  step   600  loss 1.0124
  epoch  1  step   700  loss 1.0053
  epoch  1  step   800  loss 0.9984
  epoch  1  step   900  loss 0.9954
  epoch  1  step  1000  loss 0.9876
  epoch  1  step  1100  loss 0.9830
  epoch  1  step  1200  loss 0.9804
  epoch  1  step  1300  loss 0.9802
  epoch  1  step  1400  loss 0.9787
  epoch  1 done  (24.4s)   train_loss=0.9771   val_acc=0.5620
  epoch  2  step   100  loss 0.7733
  epoch  2  step   200  loss 0.7710
  epoch  2  step   300  loss 0.7672
  epoch  2  step   400  loss 0.7574
  epoch  2  step   500  loss 0.7583
  epoch  2  step   600  loss 0.7487
  epoch  2  step   700  loss 0.7445
  epoch  2  step   800  loss 0.7469
  epoch  2  step   900  loss 0.7442
  epoch  2  step  1000  loss 0.7390
  epoch  2  step  1100  loss 0.7383
  epoch  2  step  1200  loss 0.7396
  epoch  2  step  1300  loss 0.7406
  epoch  2  step  1400  loss 0.7394
  epoch  2 done  (17.1s)   train_loss=0.7434   val_acc=0.6891
  epoch  3  step   100  loss 0.5441
  epoch  3  step   200  loss 0.5218
  epoch  3  step   300  loss 0.5195
  epoch  3  step   400  loss 0.5146
  epoch  3  step   500  loss 0.5158
  epoch  3  step   600  loss 0.5190
  epoch  3  step   700  loss 0.5219
  epoch  3  step   800  loss 0.5229
  epoch  3  step   900  loss 0.5246
  epoch  3  step  1000  loss 0.5243
  epoch  3  step  1100  loss 0.5289
  epoch  3  step  1200  loss 0.5305
  epoch  3  step  1300  loss 0.5367
  epoch  3  step  1400  loss 0.5402
  epoch  3 done  (15.6s)   train_loss=0.5399   val_acc=0.7038
  epoch  4  step   100  loss 0.4070
  epoch  4  step   200  loss 0.4100
  epoch  4  step   300  loss 0.4194
  epoch  4  step   400  loss 0.4174
  epoch  4  step   500  loss 0.4157
  epoch  4  step   600  loss 0.4189
  epoch  4  step   700  loss 0.4224
  epoch  4  step   800  loss 0.4209
  epoch  4  step   900  loss 0.4244
  epoch  4  step  1000  loss 0.4234
  epoch  4  step  1100  loss 0.4288
  epoch  4  step  1200  loss 0.4307
  epoch  4  step  1300  loss 0.4313
  epoch  4  step  1400  loss 0.4311
  epoch  4 done  (16.5s)   train_loss=0.4345   val_acc=0.6777
  epoch  5  step   100  loss 0.3406
  epoch  5  step   200  loss 0.3439
  epoch  5  step   300  loss 0.3466
  epoch  5  step   400  loss 0.3488
  epoch  5  step   500  loss 0.3563
  epoch  5  step   600  loss 0.3575
  epoch  5  step   700  loss 0.3593
  epoch  5  step   800  loss 0.3630
  epoch  5  step   900  loss 0.3659
  epoch  5  step  1000  loss 0.3669
  epoch  5  step  1100  loss 0.3693
  epoch  5  step  1200  loss 0.3739
  epoch  5  step  1300  loss 0.3767
  epoch  5  step  1400  loss 0.3774
  epoch  5 done  (15.5s)   train_loss=0.3782   val_acc=0.7617
  epoch  6  step   100  loss 0.3292
  epoch  6  step   200  loss 0.3210
  epoch  6  step   300  loss 0.3184
  epoch  6  step   400  loss 0.3186
  epoch  6  step   500  loss 0.3195
  epoch  6  step   600  loss 0.3198
  epoch  6  step   700  loss 0.3178
  epoch  6  step   800  loss 0.3189
  epoch  6  step   900  loss 0.3212
  epoch  6  step  1000  loss 0.3227
  epoch  6  step  1100  loss 0.3227
  epoch  6  step  1200  loss 0.3249
  epoch  6  step  1300  loss 0.3303
  epoch  6  step  1400  loss 0.3322
  epoch  6 done  (15.8s)   train_loss=0.3324   val_acc=0.7786
  epoch  7  step   100  loss 0.2725
  epoch  7  step   200  loss 0.2790
  epoch  7  step   300  loss 0.2837
  epoch  7  step   400  loss 0.2800
  epoch  7  step   500  loss 0.2779
  epoch  7  step   600  loss 0.2839
  epoch  7  step   700  loss 0.2872
  epoch  7  step   800  loss 0.2903
  epoch  7  step   900  loss 0.2897
  epoch  7  step  1000  loss 0.2940
  epoch  7  step  1100  loss 0.2958
  epoch  7  step  1200  loss 0.2956
  epoch  7  step  1300  loss 0.2972
  epoch  7  step  1400  loss 0.3006
  epoch  7 done  (15.4s)   train_loss=0.3007   val_acc=0.7827
  epoch  8  step   100  loss 0.2573
  epoch  8  step   200  loss 0.2594
  epoch  8  step   300  loss 0.2599
  epoch  8  step   400  loss 0.2671
  epoch  8  step   500  loss 0.2640
  epoch  8  step   600  loss 0.2692
  epoch  8  step   700  loss 0.2719
  epoch  8  step   800  loss 0.2736
  epoch  8  step   900  loss 0.2746
  epoch  8  step  1000  loss 0.2768
  epoch  8  step  1100  loss 0.2781
  epoch  8  step  1200  loss 0.2789
  epoch  8  step  1300  loss 0.2818
  epoch  8  step  1400  loss 0.2812
  epoch  8 done  (16.1s)   train_loss=0.2822   val_acc=0.7373
  TEST  acc=0.7848  macro-F1=0.4533  weighted-F1=0.8117

=== SENTIMENT — BILSTM ===
  sentiment vocab: 58,851 tokens (pad_id=0, unk_id=1)
  trainable params: 20,639,751
  class weights: [2.4632327556610107, 114.76207733154297, 0.38679996132850647]
  epoch  1  step   100  loss 1.0675
  epoch  1  step   200  loss 1.0578
  epoch  1  step   300  loss 1.0440
  epoch  1  step   400  loss 1.0407
  epoch  1  step   500  loss 1.0310
  epoch  1  step   600  loss 1.0237
  epoch  1  step   700  loss 1.0167
  epoch  1  step   800  loss 1.0108
  epoch  1  step   900  loss 1.0072
  epoch  1  step  1000  loss 1.0019
  epoch  1  step  1100  loss 0.9940
  epoch  1  step  1200  loss 0.9893
  epoch  1  step  1300  loss 0.9847
  epoch  1  step  1400  loss 0.9784
  epoch  1 done  (37.5s)   train_loss=0.9771   val_acc=0.6579
  epoch  2  step   100  loss 0.7872
  epoch  2  step   200  loss 0.7826
  epoch  2  step   300  loss 0.7673
  epoch  2  step   400  loss 0.7717
  epoch  2  step   500  loss 0.7652
  epoch  2  step   600  loss 0.7659
  epoch  2  step   700  loss 0.7715
  epoch  2  step   800  loss 0.7724
  epoch  2  step   900  loss 0.7710
  epoch  2  step  1000  loss 0.7733
  epoch  2  step  1100  loss 0.7694
  epoch  2  step  1200  loss 0.7722
  epoch  2  step  1300  loss 0.7746
  epoch  2  step  1400  loss 0.7743
  epoch  2 done  (38.5s)   train_loss=0.7751   val_acc=0.6774
  epoch  3  step   100  loss 0.5957
  epoch  3  step   200  loss 0.5950
  epoch  3  step   300  loss 0.5796
  epoch  3  step   400  loss 0.5802
  epoch  3  step   500  loss 0.5794
  epoch  3  step   600  loss 0.5707
  epoch  3  step   700  loss 0.5731
  epoch  3  step   800  loss 0.5708
  epoch  3  step   900  loss 0.5720
  epoch  3  step  1000  loss 0.5735
  epoch  3  step  1100  loss 0.5750
  epoch  3  step  1200  loss 0.5803
  epoch  3  step  1300  loss 0.5804
  epoch  3  step  1400  loss 0.5820
  epoch  3 done  (40.4s)   train_loss=0.5841   val_acc=0.6928
  epoch  4  step   100  loss 0.4542
  epoch  4  step   200  loss 0.4583
  epoch  4  step   300  loss 0.4632
  epoch  4  step   400  loss 0.4528
  epoch  4  step   500  loss 0.4579
  epoch  4  step   600  loss 0.4579
  epoch  4  step   700  loss 0.4570
  epoch  4  step   800  loss 0.4662
  epoch  4  step   900  loss 0.4692
  epoch  4  step  1000  loss 0.4728
  epoch  4  step  1100  loss 0.4732
  epoch  4  step  1200  loss 0.4704
  epoch  4  step  1300  loss 0.4701
  epoch  4  step  1400  loss 0.4734
  epoch  4 done  (40.7s)   train_loss=0.4736   val_acc=0.6794
  epoch  5  step   100  loss 0.3687
  epoch  5  step   200  loss 0.3776
  epoch  5  step   300  loss 0.3943
  epoch  5  step   400  loss 0.3980
  epoch  5  step   500  loss 0.4023
  epoch  5  step   600  loss 0.4052
  epoch  5  step   700  loss 0.4018
  epoch  5  step   800  loss 0.4026
  epoch  5  step   900  loss 0.4007
  epoch  5  step  1000  loss 0.4025
  epoch  5  step  1100  loss 0.4022
  epoch  5  step  1200  loss 0.4018
  epoch  5  step  1300  loss 0.4018
  epoch  5  step  1400  loss 0.4032
  epoch  5 done  (40.8s)   train_loss=0.4056   val_acc=0.6750
  epoch  6  step   100  loss 0.3449
  epoch  6  step   200  loss 0.3372
  epoch  6  step   300  loss 0.3354
  epoch  6  step   400  loss 0.3423
  epoch  6  step   500  loss 0.3438
  epoch  6  step   600  loss 0.3435
  epoch  6  step   700  loss 0.3418
  epoch  6  step   800  loss 0.3410
  epoch  6  step   900  loss 0.3411
  epoch  6  step  1000  loss 0.3417
  epoch  6  step  1100  loss 0.3413
  epoch  6  step  1200  loss 0.3389
  epoch  6  step  1300  loss 0.3390
  epoch  6  step  1400  loss 0.3382
  epoch  6 done  (41.1s)   train_loss=0.3378   val_acc=0.7486
  epoch  7  step   100  loss 0.2967
  epoch  7  step   200  loss 0.3075
  epoch  7  step   300  loss 0.2957
  epoch  7  step   400  loss 0.3029
  epoch  7  step   500  loss 0.2984
  epoch  7  step   600  loss 0.2959
  epoch  7  step   700  loss 0.2999
  epoch  7  step   800  loss 0.2994
  epoch  7  step   900  loss 0.2988
  epoch  7  step  1000  loss 0.3000
  epoch  7  step  1100  loss 0.3009
  epoch  7  step  1200  loss 0.3039
  epoch  7  step  1300  loss 0.3037
  epoch  7  step  1400  loss 0.3064
  epoch  7 done  (39.3s)   train_loss=0.3067   val_acc=0.7450
  epoch  8  step   100  loss 0.2737
  epoch  8  step   200  loss 0.2680
  epoch  8  step   300  loss 0.2680
  epoch  8  step   400  loss 0.2678
  epoch  8  step   500  loss 0.2662
  epoch  8  step   600  loss 0.2690
  epoch  8  step   700  loss 0.2691
  epoch  8  step   800  loss 0.2704
  epoch  8  step   900  loss 0.2707
  epoch  8  step  1000  loss 0.2754
  epoch  8  step  1100  loss 0.2761
  epoch  8  step  1200  loss 0.2776
  epoch  8  step  1300  loss 0.2776
  epoch  8  step  1400  loss 0.2783
  epoch  8 done  (34.0s)   train_loss=0.2786   val_acc=0.7758
  TEST  acc=0.7762  macro-F1=0.4500  weighted-F1=0.8040

In [12]:
run_dl("emotion", "cnn")
run_dl("emotion", "bilstm")

=== EMOTION — CNN ===
  emotion vocab: 58,803 tokens (pad_id=0, unk_id=1)
  trainable params: 18,104,394
  class weights: [0.19339998066425323, 1.7623409032821655, 31.722137451171875, 48.32322311401367, 5.2003068923950195, 57.381038665771484]
  epoch  1  step   100  loss 1.7775
  epoch  1  step   200  loss 1.7671
  epoch  1  step   300  loss 1.7481
  epoch  1  step   400  loss 1.7310
  epoch  1  step   500  loss 1.7159
  epoch  1  step   600  loss 1.7089
  epoch  1  step   700  loss 1.6996
  epoch  1  step   800  loss 1.6905
  epoch  1  step   900  loss 1.6840
  epoch  1  step  1000  loss 1.6731
  epoch  1  step  1100  loss 1.6641
  epoch  1  step  1200  loss 1.6577
  epoch  1  step  1300  loss 1.6511
  epoch  1  step  1400  loss 1.6459
  epoch  1 done  (14.6s)   train_loss=1.6427   val_acc=0.4690
  epoch  2  step   100  loss 1.2911
  epoch  2  step   200  loss 1.2642
  epoch  2  step   300  loss 1.2607
  epoch  2  step   400  loss 1.2656
  epoch  2  step   500  loss 1.2765
  epoch  2  step   600  loss 1.2786
  epoch  2  step   700  loss 1.2706
  epoch  2  step   800  loss 1.2666
  epoch  2  step   900  loss 1.2703
  epoch  2  step  1000  loss 1.2729
  epoch  2  step  1100  loss 1.2741
  epoch  2  step  1200  loss 1.2760
  epoch  2  step  1300  loss 1.2780
  epoch  2  step  1400  loss 1.2782
  epoch  2 done  (14.3s)   train_loss=1.2788   val_acc=0.4316
  epoch  3  step   100  loss 0.8614
  epoch  3  step   200  loss 0.8621
  epoch  3  step   300  loss 0.8395
  epoch  3  step   400  loss 0.8391
  epoch  3  step   500  loss 0.8390
  epoch  3  step   600  loss 0.8406
  epoch  3  step   700  loss 0.8447
  epoch  3  step   800  loss 0.8492
  epoch  3  step   900  loss 0.8558
  epoch  3  step  1000  loss 0.8652
  epoch  3  step  1100  loss 0.8691
  epoch  3  step  1200  loss 0.8760
  epoch  3  step  1300  loss 0.8821
  epoch  3  step  1400  loss 0.8858
  epoch  3 done  (14.5s)   train_loss=0.8881   val_acc=0.5177
  epoch  4  step   100  loss 0.6161
  epoch  4  step   200  loss 0.6260
  epoch  4  step   300  loss 0.6326
  epoch  4  step   400  loss 0.6383
  epoch  4  step   500  loss 0.6379
  epoch  4  step   600  loss 0.6432
  epoch  4  step   700  loss 0.6442
  epoch  4  step   800  loss 0.6468
  epoch  4  step   900  loss 0.6539
  epoch  4  step  1000  loss 0.6566
  epoch  4  step  1100  loss 0.6580
  epoch  4  step  1200  loss 0.6595
  epoch  4  step  1300  loss 0.6654
  epoch  4  step  1400  loss 0.6680
  epoch  4 done  (14.6s)   train_loss=0.6723   val_acc=0.5296
  epoch  5  step   100  loss 0.5238
  epoch  5  step   200  loss 0.5086
  epoch  5  step   300  loss 0.5292
  epoch  5  step   400  loss 0.5335
  epoch  5  step   500  loss 0.5311
  epoch  5  step   600  loss 0.5415
  epoch  5  step   700  loss 0.5471
  epoch  5  step   800  loss 0.5492
  epoch  5  step   900  loss 0.5522
  epoch  5  step  1000  loss 0.5587
  epoch  5  step  1100  loss 0.5636
  epoch  5  step  1200  loss 0.5662
  epoch  5  step  1300  loss 0.5676
  epoch  5  step  1400  loss 0.5721
  epoch  5 done  (14.2s)   train_loss=0.5740   val_acc=0.5466
  epoch  6  step   100  loss 0.4862
  epoch  6  step   200  loss 0.4760
  epoch  6  step   300  loss 0.4674
  epoch  6  step   400  loss 0.4771
  epoch  6  step   500  loss 0.4781
  epoch  6  step   600  loss 0.4815
  epoch  6  step   700  loss 0.4882
  epoch  6  step   800  loss 0.4873
  epoch  6  step   900  loss 0.4891
  epoch  6  step  1000  loss 0.4935
  epoch  6  step  1100  loss 0.4939
  epoch  6  step  1200  loss 0.5014
  epoch  6  step  1300  loss 0.5062
  epoch  6  step  1400  loss 0.5095
  epoch  6 done  (15.2s)   train_loss=0.5121   val_acc=0.6459
  epoch  7  step   100  loss 0.4294
  epoch  7  step   200  loss 0.4301
  epoch  7  step   300  loss 0.4310
  epoch  7  step   400  loss 0.4342
  epoch  7  step   500  loss 0.4358
  epoch  7  step   600  loss 0.4410
  epoch  7  step   700  loss 0.4390
  epoch  7  step   800  loss 0.4384
  epoch  7  step   900  loss 0.4429
  epoch  7  step  1000  loss 0.4476
  epoch  7  step  1100  loss 0.4509
  epoch  7  step  1200  loss 0.4533
  epoch  7  step  1300  loss 0.4573
  epoch  7  step  1400  loss 0.4620
  epoch  7 done  (15.3s)   train_loss=0.4627   val_acc=0.5695
  epoch  8  step   100  loss 0.4085
  epoch  8  step   200  loss 0.3920
  epoch  8  step   300  loss 0.3861
  epoch  8  step   400  loss 0.3819
  epoch  8  step   500  loss 0.3869
  epoch  8  step   600  loss 0.3936
  epoch  8  step   700  loss 0.3982
  epoch  8  step   800  loss 0.4079
  epoch  8  step   900  loss 0.4169
  epoch  8  step  1000  loss 0.4214
  epoch  8  step  1100  loss 0.4277
  epoch  8  step  1200  loss 0.4308
  epoch  8  step  1300  loss 0.4332
  epoch  8  step  1400  loss 0.4347
  epoch  8 done  (15.6s)   train_loss=0.4360   val_acc=0.6050
  TEST  acc=0.6476  macro-F1=0.2499  weighted-F1=0.7215

=== EMOTION — BILSTM ===
  emotion vocab: 58,803 tokens (pad_id=0, unk_id=1)
  trainable params: 20,626,890
  class weights: [0.19339998066425323, 1.7623409032821655, 31.722137451171875, 48.32322311401367, 5.2003068923950195, 57.381038665771484]
  epoch  1  step   100  loss 1.7809
  epoch  1  step   200  loss 1.7577
  epoch  1  step   300  loss 1.7426
  epoch  1  step   400  loss 1.7266
  epoch  1  step   500  loss 1.7259
  epoch  1  step   600  loss 1.7204
  epoch  1  step   700  loss 1.7113
  epoch  1  step   800  loss 1.7019
  epoch  1  step   900  loss 1.6925
  epoch  1  step  1000  loss 1.6821
  epoch  1  step  1100  loss 1.6750
  epoch  1  step  1200  loss 1.6706
  epoch  1  step  1300  loss 1.6627
  epoch  1  step  1400  loss 1.6553
  epoch  1 done  (34.0s)   train_loss=1.6545   val_acc=0.4242
  epoch  2  step   100  loss 1.3332
  epoch  2  step   200  loss 1.3361
  epoch  2  step   300  loss 1.3338
  epoch  2  step   400  loss 1.3296
  epoch  2  step   500  loss 1.3438
  epoch  2  step   600  loss 1.3404
  epoch  2  step   700  loss 1.3406
  epoch  2  step   800  loss 1.3393
  epoch  2  step   900  loss 1.3389
  epoch  2  step  1000  loss 1.3373
  epoch  2  step  1100  loss 1.3379
  epoch  2  step  1200  loss 1.3373
  epoch  2  step  1300  loss 1.3386
  epoch  2  step  1400  loss 1.3418
  epoch  2 done  (32.4s)   train_loss=1.3415   val_acc=0.3909
  epoch  3  step   100  loss 0.9305
  epoch  3  step   200  loss 0.9104
  epoch  3  step   300  loss 0.9209
  epoch  3  step   400  loss 0.9340
  epoch  3  step   500  loss 0.9375
  epoch  3  step   600  loss 0.9552
  epoch  3  step   700  loss 0.9595
  epoch  3  step   800  loss 0.9683
  epoch  3  step   900  loss 0.9776
  epoch  3  step  1000  loss 0.9769
  epoch  3  step  1100  loss 0.9803
  epoch  3  step  1200  loss 0.9852
  epoch  3  step  1300  loss 0.9881
  epoch  3  step  1400  loss 0.9890
  epoch  3 done  (32.2s)   train_loss=0.9896   val_acc=0.4934
  epoch  4  step   100  loss 0.7080
  epoch  4  step   200  loss 0.7070
  epoch  4  step   300  loss 0.6968
  epoch  4  step   400  loss 0.6959
  epoch  4  step   500  loss 0.7056
  epoch  4  step   600  loss 0.7093
  epoch  4  step   700  loss 0.7110
  epoch  4  step   800  loss 0.7149
  epoch  4  step   900  loss 0.7203
  epoch  4  step  1000  loss 0.7256
  epoch  4  step  1100  loss 0.7306
  epoch  4  step  1200  loss 0.7340
  epoch  4  step  1300  loss 0.7380
  epoch  4  step  1400  loss 0.7445
  epoch  4 done  (32.1s)   train_loss=0.7460   val_acc=0.5704
  epoch  5  step   100  loss 0.5866
  epoch  5  step   200  loss 0.5797
  epoch  5  step   300  loss 0.5721
  epoch  5  step   400  loss 0.5765
  epoch  5  step   500  loss 0.5807
  epoch  5  step   600  loss 0.5863
  epoch  5  step   700  loss 0.5908
  epoch  5  step   800  loss 0.5938
  epoch  5  step   900  loss 0.5988
  epoch  5  step  1000  loss 0.6049
  epoch  5  step  1100  loss 0.6075
  epoch  5  step  1200  loss 0.6086
  epoch  5  step  1300  loss 0.6132
  epoch  5  step  1400  loss 0.6172
  epoch  5 done  (32.1s)   train_loss=0.6192   val_acc=0.5211
  epoch  6  step   100  loss 0.5266
  epoch  6  step   200  loss 0.5107
  epoch  6  step   300  loss 0.5080
  epoch  6  step   400  loss 0.5122
  epoch  6  step   500  loss 0.5142
  epoch  6  step   600  loss 0.5164
  epoch  6  step   700  loss 0.5178
  epoch  6  step   800  loss 0.5224
  epoch  6  step   900  loss 0.5263
  epoch  6  step  1000  loss 0.5331
  epoch  6  step  1100  loss 0.5384
  epoch  6  step  1200  loss 0.5432
  epoch  6  step  1300  loss 0.5475
  epoch  6  step  1400  loss 0.5528
  epoch  6 done  (32.8s)   train_loss=0.5547   val_acc=0.5219
  epoch  7  step   100  loss 0.4941
  epoch  7  step   200  loss 0.4819
  epoch  7  step   300  loss 0.4672
  epoch  7  step   400  loss 0.4555
  epoch  7  step   500  loss 0.4548
  epoch  7  step   600  loss 0.4570
  epoch  7  step   700  loss 0.4541
  epoch  7  step   800  loss 0.4570
  epoch  7  step   900  loss 0.4569
  epoch  7  step  1000  loss 0.4539
  epoch  7  step  1100  loss 0.4522
  epoch  7  step  1200  loss 0.4515
  epoch  7  step  1300  loss 0.4499
  epoch  7  step  1400  loss 0.4496
  epoch  7 done  (33.2s)   train_loss=0.4494   val_acc=0.5948
  epoch  8  step   100  loss 0.3791
  epoch  8  step   200  loss 0.3830
  epoch  8  step   300  loss 0.3782
  epoch  8  step   400  loss 0.3785
  epoch  8  step   500  loss 0.3779
  epoch  8  step   600  loss 0.3804
  epoch  8  step   700  loss 0.3828
  epoch  8  step   800  loss 0.3872
  epoch  8  step   900  loss 0.3929
  epoch  8  step  1000  loss 0.3947
  epoch  8  step  1100  loss 0.3957
  epoch  8  step  1200  loss 0.4000
  epoch  8  step  1300  loss 0.4010
  epoch  8  step  1400  loss 0.4012
  epoch  8 done  (33.7s)   train_loss=0.4002   val_acc=0.6077
  TEST  acc=0.6064  macro-F1=0.2428  weighted-F1=0.6910

## 7 — Transformer fine-tuning: mBERT, XLM-RoBERTa, Urdu-RoBERTa

HuggingFace Trainer with class-weighted cross-entropy, fp16, and the
standard warm-up + linear-decay schedule (§6.3 of the math doc).

In [8]:
from train_transformer import TransformerCfg, finetune_transformer

def transformer_class_weights(labels_arr, num_classes):
    from sklearn.utils.class_weight import compute_class_weight
    cls = np.arange(num_classes)
    return compute_class_weight(class_weight="balanced", classes=cls, y=labels_arr).tolist()

def run_transformer(task: str, model_key: str):
    cfg_dict = config.TRANSFORMERS[model_key]
    cfg = TransformerCfg(name=model_key, max_len=config.TRANSFORMER_MAX_LEN, **cfg_dict)
    tr, va, te = splits[task]["train"], splits[task]["val"], splits[task]["test"]
    if TRANSFORMER_TRAIN_SUBSET:
        tr = tr.groupby("label", group_keys=False).apply(
            lambda g: g.sample(min(len(g), max(1, int(len(g)*TRANSFORMER_TRAIN_SUBSET/len(tr)))),
                               random_state=SEED)
        ).reset_index(drop=True)

    if task == "sentiment":
        id2label = {i: l for i, l in enumerate(["Negative", "Neutral", "Positive"])}
    else:
        id2label = {i: l for i, l in enumerate(EMOTION_LABELS)}
    label2id = {v: k for k, v in id2label.items()}

    cw = transformer_class_weights(tr["label"].values, num_classes=len(id2label))
    print(f"  {task}/{model_key}: train={len(tr):,}, weights={cw}")

    res = finetune_transformer(
        cfg=cfg, train_df=tr, val_df=va, test_df=te,
        text_col="clean_text", label_col="label",
        id2label=id2label, label2id=label2id,
        class_weights=cw, output_root=MODEL_DIR,
        task_name=task,
    )
    # Save predictions in the standard location too:
    preds = pd.read_csv(Path(res["output_dir"]) / "test_predictions.csv")
    preds.to_csv(RESULTS_DIR / f"pred_{task}_{model_key}.csv", index=False)
    return res

In [14]:
# Sentiment task
run_transformer("sentiment", "mbert")

  sentiment/mbert: train=372,862, weights=[2.4632327196094366, 114.76208064019698, 0.38679994937580786]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 372862/372862 [00:05<00:00, 63004.41 examples/s]
Map: 100%|██████████| 79899/79899 [00:01<00:00, 64890.16 examples/s]
Map: 100%|██████████| 79900/79900 [00:01<00:00, 61229.83 examples/s]

{'preds': array([2, 2, 2, ..., 2, 2, 2], shape=(79900,)),
 'metrics': {'task': 'sentiment',
  'model': 'mbert',
  'val': {'eval_loss': 1.031615138053894,
   'eval_accuracy': 0.8042653850486239,
   'eval_f1_macro': 0.4463866159547161,
   'eval_f1_weighted': 0.8206512532091891,
   'eval_runtime': 29.5797,
   'eval_samples_per_second': 2701.142,
   'eval_steps_per_second': 42.225,
   'epoch': 3.0},
  'test': {'test_loss': 1.0111902952194214,
   'test_accuracy': 0.8054443053817272,
   'test_f1_macro': 0.4526474913567841,
   'test_f1_weighted': 0.8216717045885426,
   'test_runtime': 30.2856,
   'test_samples_per_second': 2638.222,
   'test_steps_per_second': 41.241}},
 'output_dir': 'C:\\Users\\USER\\Desktop\\NLP Project\\Assignment#03\\outputs\\models\\mbert_sentiment'}

In [9]:
run_transformer("sentiment", "xlm-r")

  sentiment/xlm-r: train=372,862, weights=[2.4632327196094366, 114.76208064019698, 0.38679994937580786]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 372862/372862 [00:04<00:00, 81277.21 examples/s]
Map: 100%|██████████| 79899/79899 [00:01<00:00, 78840.28 examples/s]
Map: 100%|██████████| 79900/79900 [00:00<00:00, 97068.77 examples/s]

{'preds': array([0, 2, 2, ..., 0, 2, 0], shape=(79900,)),
 'metrics': {'task': 'sentiment',
  'model': 'xlm-r',
  'val': {'eval_loss': 1.070328712463379,
   'eval_accuracy': 0.785216335623725,
   'eval_f1_macro': 0.438253518163698,
   'eval_f1_weighted': 0.8080666145212567,
   'eval_runtime': 27.1832,
   'eval_samples_per_second': 2939.279,
   'eval_steps_per_second': 45.947,
   'epoch': 3.0},
  'test': {'test_loss': 1.0338211059570312,
   'test_accuracy': 0.7896620775969962,
   'test_f1_macro': 0.4474681701307377,
   'test_f1_weighted': 0.8118390687494448,
   'test_runtime': 28.2338,
   'test_samples_per_second': 2829.937,
   'test_steps_per_second': 44.238}},
 'output_dir': 'C:\\Users\\USER\\Desktop\\NLP Project\\Assignment#03\\outputs\\models\\xlm-r_sentiment'}

In [10]:
run_transformer("sentiment", "urdu-roberta")

  sentiment/urdu-roberta: train=372,862, weights=[2.4632327196094366, 114.76208064019698, 0.38679994937580786]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at urduhack/roberta-urdu-small and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 372862/372862 [00:04<00:00, 88159.26 examples/s]
Map: 100%|██████████| 79899/79899 [00:00<00:00, 80950.39 examples/s]
Map: 100%|██████████| 79900/79900 [00:00<00:00, 89126.09 examples/s]

{'preds': array([0, 2, 2, ..., 0, 2, 2], shape=(79900,)),
 'metrics': {'task': 'sentiment',
  'model': 'urdu-roberta',
  'val': {'eval_loss': 1.257526159286499,
   'eval_accuracy': 0.7731761348702737,
   'eval_f1_macro': 0.4408270609146778,
   'eval_f1_weighted': 0.7995229494359467,
   'eval_runtime': 28.3244,
   'eval_samples_per_second': 2820.851,
   'eval_steps_per_second': 22.066,
   'epoch': 3.0},
  'test': {'test_loss': 1.2419825792312622,
   'test_accuracy': 0.7750187734668336,
   'test_f1_macro': 0.45725950008236116,
   'test_f1_weighted': 0.8010672089604743,
   'test_runtime': 28.724,
   'test_samples_per_second': 2781.647,
   'test_steps_per_second': 21.759}},
 'output_dir': 'C:\\Users\\USER\\Desktop\\NLP Project\\Assignment#03\\outputs\\models\\urdu-roberta_sentiment'}

In [11]:
# Emotion task
run_transformer("emotion", "mbert")

  emotion/mbert: train=372,862, weights=[0.19339997468790393, 1.7623409524889873, 31.72213714480177, 48.323224468636596, 5.200306834030683, 57.38104032009849]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 372862/372862 [00:05<00:00, 67605.18 examples/s]
Map: 100%|██████████| 79899/79899 [00:01<00:00, 63280.99 examples/s]
Map: 100%|██████████| 79900/79900 [00:01<00:00, 69261.52 examples/s]

{'preds': array([0, 4, 0, ..., 0, 0, 1], shape=(79900,)),
 'metrics': {'task': 'emotion',
  'model': 'mbert',
  'val': {'eval_loss': 1.7606559991836548,
   'eval_accuracy': 0.690709520769972,
   'eval_f1_macro': 0.26064096694905237,
   'eval_f1_weighted': 0.7460175522239072,
   'eval_runtime': 31.0912,
   'eval_samples_per_second': 2569.83,
   'eval_steps_per_second': 40.172,
   'epoch': 3.0},
  'test': {'test_loss': 1.7260329723358154,
   'test_accuracy': 0.6922403003754694,
   'test_f1_macro': 0.2703445759299271,
   'test_f1_weighted': 0.7467129005295166,
   'test_runtime': 32.4366,
   'test_samples_per_second': 2463.266,
   'test_steps_per_second': 38.506}},
 'output_dir': 'C:\\Users\\USER\\Desktop\\NLP Project\\Assignment#03\\outputs\\models\\mbert_emotion'}

In [12]:
run_transformer("emotion", "xlm-r")

  emotion/xlm-r: train=372,862, weights=[0.19339997468790393, 1.7623409524889873, 31.72213714480177, 48.323224468636596, 5.200306834030683, 57.38104032009849]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 372862/372862 [00:08<00:00, 44539.32 examples/s]
Map: 100%|██████████| 79899/79899 [00:02<00:00, 39402.48 examples/s]
Map: 100%|██████████| 79900/79900 [00:01<00:00, 50210.88 examples/s]

{'preds': array([0, 0, 0, ..., 0, 0, 1], shape=(79900,)),
 'metrics': {'task': 'emotion',
  'model': 'xlm-r',
  'val': {'eval_loss': 1.7649590969085693,
   'eval_accuracy': 0.6896581934692549,
   'eval_f1_macro': 0.25350118201590016,
   'eval_f1_weighted': 0.7459648560797835,
   'eval_runtime': 27.6409,
   'eval_samples_per_second': 2890.611,
   'eval_steps_per_second': 45.187,
   'epoch': 3.0},
  'test': {'test_loss': 1.7508302927017212,
   'test_accuracy': 0.6906633291614518,
   'test_f1_macro': 0.25353298028217147,
   'test_f1_weighted': 0.7461967712177684,
   'test_runtime': 28.1583,
   'test_samples_per_second': 2837.525,
   'test_steps_per_second': 44.356}},
 'output_dir': 'C:\\Users\\USER\\Desktop\\NLP Project\\Assignment#03\\outputs\\models\\xlm-r_emotion'}

In [13]:
run_transformer("emotion", "urdu-roberta")

  emotion/urdu-roberta: train=372,862, weights=[0.19339997468790393, 1.7623409524889873, 31.72213714480177, 48.323224468636596, 5.200306834030683, 57.38104032009849]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at urduhack/roberta-urdu-small and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 372862/372862 [00:04<00:00, 84576.54 examples/s]
Map: 100%|██████████| 79899/79899 [00:00<00:00, 81572.61 examples/s]
Map: 100%|██████████| 79900/79900 [00:00<00:00, 91134.03 examples/s]

{'preds': array([0, 0, 0, ..., 0, 0, 4], shape=(79900,)),
 'metrics': {'task': 'emotion',
  'model': 'urdu-roberta',
  'val': {'eval_loss': 1.8412840366363525,
   'eval_accuracy': 0.6139876594200178,
   'eval_f1_macro': 0.2477142321532995,
   'eval_f1_weighted': 0.6958404332997518,
   'eval_runtime': 30.0859,
   'eval_samples_per_second': 2655.695,
   'eval_steps_per_second': 20.774,
   'epoch': 3.0},
  'test': {'test_loss': 1.7951668500900269,
   'test_accuracy': 0.6153441802252816,
   'test_f1_macro': 0.25393742918887724,
   'test_f1_weighted': 0.6971450817608247,
   'test_runtime': 30.448,
   'test_samples_per_second': 2624.149,
   'test_steps_per_second': 20.527}},
 'output_dir': 'C:\\Users\\USER\\Desktop\\NLP Project\\Assignment#03\\outputs\\models\\urdu-roberta_emotion'}

## 8 — Inference demo on hand-crafted tweets

In [14]:
import joblib
from transformers import AutoModelForSequenceClassification, AutoTokenizer

demo = [
    "آج کا دن بہت اچھا تھا یہ واقعی خوبصورت لمحہ ہے",         # positive / joy
    "حکومت کی پالیسیاں بالکل غلط ہیں کوئی بہتری نہیں آئی",     # negative / anger
    "یہ خبر سن کر بہت حیرت ہوئی واقعی عجیب بات ہے",            # neutral / surprise
    "والد کی محبت سے زیادہ کوئی نعمت نہیں",                    # positive / love
    "ہمارا ساتھی شدید بیمار ہو گیا ہے اللہ کرم کرے",            # negative / fear or sadness
]
print("Demo tweets (cleaned):")
for t in demo:
    print("  ", pp.preprocess_tweet(t))

Demo tweets (cleaned):
   آج کا دن بہت اچھا تھا یہ واقعی خوبصورت لمحہ ہے
   حکومت کی پالیسیاں بالکل غلط ہیں کوئی بہتری نہیں آئی
   یہ خبر سن کر بہت حیرت ہوئی واقعی عجیب بات ہے
   والد کی محبت سے زیادہ کوئی نعمت نہیں
   ہمارا ساتھی شدید بیمار ہو گیا ہے اللہ کرم کرے

In [15]:
# Pick the best transformer per task by val macro-F1 logged in metrics.json
import glob
def pick_best(task):
    cands = []
    for d in glob.glob(str(MODEL_DIR / f"*_{task}")):
        mp = Path(d) / "metrics.json"
        if mp.exists():
            m = json.loads(mp.read_text(encoding="utf-8"))
            cands.append((m["val"].get("eval_f1_macro", 0), d, m["model"]))
    cands.sort(reverse=True)
    return cands[0] if cands else None

for task in ("sentiment", "emotion"):
    pick = pick_best(task)
    if pick is None:
        print(f"  no transformer trained yet for {task}")
        continue
    score, dpath, mname = pick
    print(f"\nBest transformer for {task}: {mname} (val_f1_macro={score:.4f})  -> {dpath}")
    tok = AutoTokenizer.from_pretrained(str(Path(dpath) / "best"))
    mdl = AutoModelForSequenceClassification.from_pretrained(str(Path(dpath) / "best"))
    mdl.eval()
    with torch.no_grad():
        for t in demo:
            inp = tok([pp.preprocess_tweet(t)], padding=True, truncation=True,
                      max_length=config.TRANSFORMER_MAX_LEN, return_tensors="pt")
            pred_id = int(mdl(**inp).logits.argmax(-1).item())
            lab = mdl.config.id2label[pred_id]
            print(f"  [{lab:>10}]   {t}")

The tokenizer you are loading from 'C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\models\mbert_sentiment\best' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

Best transformer for sentiment: mbert (val_f1_macro=0.4464)  -> C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\models\mbert_sentiment
  [  Positive]   آج کا دن بہت اچھا تھا یہ واقعی خوبصورت لمحہ ہے
  [  Positive]   حکومت کی پالیسیاں بالکل غلط ہیں کوئی بہتری نہیں آئی
  [  Negative]   یہ خبر سن کر بہت حیرت ہوئی واقعی عجیب بات ہے
  [  Positive]   والد کی محبت سے زیادہ کوئی نعمت نہیں
  [  Negative]   ہمارا ساتھی شدید بیمار ہو گیا ہے اللہ کرم کرے

Best transformer for emotion: mbert (val_f1_macro=0.2606)  -> C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\models\mbert_emotion

The tokenizer you are loading from 'C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\models\mbert_emotion\best' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

  [       Sad]   آج کا دن بہت اچھا تھا یہ واقعی خوبصورت لمحہ ہے
  [       Sad]   حکومت کی پالیسیاں بالکل غلط ہیں کوئی بہتری نہیں آئی
  [       Sad]   یہ خبر سن کر بہت حیرت ہوئی واقعی عجیب بات ہے
  [   Disgust]   والد کی محبت سے زیادہ کوئی نعمت نہیں
  [       Sad]   ہمارا ساتھی شدید بیمار ہو گیا ہے اللہ کرم کرے

## 9 — Summary of where everything was saved

In [16]:
print("Saved test predictions in", RESULTS_DIR)
for p in sorted(RESULTS_DIR.glob("pred_*.csv")):
    print("  ", p.name)
print("\nSaved models in", MODEL_DIR)
for p in sorted(MODEL_DIR.iterdir()):
    print("  ", p.name)

Saved test predictions in C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\results
   pred_emotion_bilstm.csv
   pred_emotion_cnn.csv
   pred_emotion_lr.csv
   pred_emotion_mbert.csv
   pred_emotion_svm.csv
   pred_emotion_urdu-roberta.csv
   pred_emotion_xlm-r.csv
   pred_sentiment_bilstm.csv
   pred_sentiment_cnn.csv
   pred_sentiment_lr.csv
   pred_sentiment_mbert.csv
   pred_sentiment_svm.csv
   pred_sentiment_urdu-roberta.csv
   pred_sentiment_xlm-r.csv

Saved models in C:\Users\USER\Desktop\NLP Project\Assignment#03\outputs\models
   bilstm_emotion.history.json
   bilstm_emotion.pt
   bilstm_sentiment.history.json
   bilstm_sentiment.pt
   cnn_emotion.history.json
   cnn_emotion.pt
   cnn_sentiment.history.json
   cnn_sentiment.pt
   lr_emotion.joblib
   lr_sentiment.joblib
   mbert_emotion
   mbert_sentiment
   svm_emotion.joblib
   svm_sentiment.joblib
   tfidf_emotion.joblib
   tfidf_sentiment.joblib
   urdu-roberta_emotion
   urdu-roberta_sentiment
   xlm-r_emotion
   xlm-r_sentiment